-- Anytime Golf — seed the course library from TrackMan's published course list
-- Run in the Supabase SQL editor after 0009_backfill_courses.sql.
--
-- Sourced from a CSV the studio owner pulled from TrackMan's own release
-- notes (support.trackmangolf.com/hc/en-us/articles/39913906600219), not
-- fabricated. Formatted as "Course Name (City, State, Country)" where the
-- source data has that detail; many entries only have a country (no
-- city/state in the source), and "Fictional" marks TrackMan's procedurally
-- generated courses that aren't based on a real place. Country is
-- abbreviated only for USA/UK/UAE, which read naturally abbreviated — other
-- countries keep their full name rather than an unfamiliar ISO code.
-- This list is only being seeded here; it does not necessarily reflect
-- which courses Anytime Golf's own TrackMan subscription actually includes.

insert into courses (name) values
  ('Abel''s Crossing (Fictional)'),
  ('Abu Dhabi Golf Club - National Course (UAE)'),
  ('Achimer 9 Hole (Germany)'),
  ('Achimer Main (Germany)'),
  ('Adare Manor (Ireland)'),
  ('Adlington (UK)'),
  ('Åkagården Golfklubb (Sweden)'),
  ('Åkersberga (Sweden)'),
  ('Albany GC (Bahamas)'),
  ('Alingsås Gk (Sweden)'),
  ('Andratx (Spain)'),
  ('Aphrodite Hills (Cyprus)'),
  ('Aronimink (Pennsylvania, USA)'),
  ('Arthur Hills GC at Boyne Resort (18) (Michigan, USA)'),
  ('Augusta Municipal - The Loop (Georgia, USA)'),
  ('Augusta Municipal - The Patch (Georgia, USA)'),
  ('Aurora International Golf Club (Anguilla)'),
  ('Bahia Beach (Puerto Rico)'),
  ('Baker''s Bay (Bahamas)'),
  ('Ballybunion: Old Course (Ireland)'),
  ('Ballyneety (UK)'),
  ('Bandon Dunes (Oregon, USA)'),
  ('Bandon Pacific Dunes (Oregon, USA)'),
  ('Bandon Preserve (Oregon, USA)'),
  ('Bandon Trails (Oregon, USA)'),
  ('Barnbougle Dunes (18 Holes) (Australia)'),
  ('Barnbougle Lost Farm (18 Holes) (Australia)'),
  ('Barnbougle Run (14 Holes) (Australia)'),
  ('Barsebäck Golf & Country Club Ocean (Sweden)'),
  ('Barsebäck Golf & Country Club Pine (Sweden)'),
  ('Båstad Golfklubb (New Course) (Sweden)'),
  ('Båstad Golfklubb (Old Course) (Sweden)'),
  ('Bay Harbor GC at Boyne Resort (27) (Michigan, USA)'),
  ('Bayou Oaks South (Louisiana, USA)'),
  ('Bear Dance GC (Colorado, USA)'),
  ('Bear Lakes Country Club (Lakes Course) (Florida, USA)'),
  ('Bellerive CC (Missouri, USA)'),
  ('Belton Woods Resort - Lakes Course (UK)'),
  ('Bernardus Golf (Netherlands)'),
  ('Bethesda CC (Maryland, USA)'),
  ('Bethpage Black (New York, USA)'),
  ('Big Sky (Canada)'),
  ('Black Desert (Utah, USA)'),
  ('Black Desert Resort (Utah, USA)'),
  ('Black Water Links (Poland)'),
  ('Blackhawk Falls Course (California, USA)'),
  ('Blackhawk Lakeside Course (California, USA)'),
  ('Blainroe Golf Club (Ireland)'),
  ('Blairgowrie Lansdowne Course (UK)'),
  ('Blairgowrie Rousemont Course (UK)'),
  ('Bobby Jones Golf Course (Azalea and Magnolia) (USA)'),
  ('Bois D''Arlon Heath (18 hole course) (Belgium)'),
  ('Bois D''Arlon Park (9 hole course) (Belgium)'),
  ('Bonarikogen Golf Club (Japan)'),
  ('Bondhay Golf Club Devonshire Course (UK)'),
  ('Bonn Godesberg (Germany)'),
  ('Bonnie Briar Country Club (New York, USA)'),
  ('Bonnie Doon (Australia)'),
  ('Bowen Island (Canada)'),
  ('Breitenloo (Switzerland)'),
  ('Brickhampton Spa Course (UK)'),
  ('Brocket Hall Golf Club (Melbourne Course) (UK)'),
  ('Brocket Hall Golf Club (Palmerston Course) (UK)'),
  ('Bromsgrove Golf Centre (UK)'),
  ('Brøndby Golfklub (Denmark)'),
  ('Bruckmannshof Golfclubb (Germany)'),
  ('Bulls Bridge Golf Club (Connecticut, USA)'),
  ('Byneset Golfklubb (North) (Norway)'),
  ('Cabot Cape Breton Cliffs (Canada)'),
  ('Cabot Cape Breton Links (Canada)'),
  ('Cabot Citrus Farms - The Roost (Florida, USA)'),
  ('Cabot Citrus Farms Karoo (Florida, USA)'),
  ('Cabot Citrus Farms Squeeze (10 Holes) (Florida, USA)'),
  ('Cabot Citrus Farms Wedge (11 Holes) (Florida, USA)'),
  ('Camiral Golf (PGA Catalunya) Stadium (Spain)'),
  ('Camiral Golf (PGA Catalunya) Tour (Spain)'),
  ('Canoe Brook Country Club (North Course) (New Jersey, USA)'),
  ('Cap De Malo (France)'),
  ('Cape Wickham (Australia)'),
  ('Casa de Campo, Dye Fore Chavon/Lagos (Dominican Republic)'),
  ('Casa de Campo, Dye Fore Lagos/Marina (Dominican Republic)'),
  ('Casa de Campo, Dye Fore Marina/Chavon (Dominican Republic)'),
  ('Casa de Campo, Teeth of the Dog (Dominican Republic)'),
  ('Chatham Hills (Indiana, USA)'),
  ('Chileno Bay (Mexico)'),
  ('Chimera GC (Nevada, USA)'),
  ('Clear Creek Tahoe (Nevada, USA)'),
  ('Clearwater Golf (New Zealand)'),
  ('Club de Golf Chapultepec (Mexico)'),
  ('Club de Golf Le Mirage Arizona Course (Canada)'),
  ('Club de Golf Le Mirage Carolina Course (Canada)'),
  ('Conway Farms (Illinois, USA)'),
  ('CostaTerra (Portugal)'),
  ('Country Club of Jackson (Mississippi, USA)'),
  ('Craig Ranch (Texas, USA)'),
  ('Crans-Sur-Sierre: Severiano Ballesteros (Switzerland)'),
  ('Crystal Pines (Fictional)'),
  ('Dalebrook Forest (Fictional)'),
  ('DaleBrook Forest (Fictional)'),
  ('Deal Golf & Country Club (New Jersey, USA)'),
  ('Dedham Country & Polo Club (Massachusetts, USA)'),
  ('Devils Island (Fictional)'),
  ('Dinsdale (UK)'),
  ('Dolomiti (Italy)'),
  ('Donalda Club (Canada)'),
  ('Dorset Golf & Country Club | Lakeland/Parkland (UK)'),
  ('Downshire Golf Complex (UK)'),
  ('Drammen GK (Norway)'),
  ('Drayton Park Golf Club (18 Hole Course) (UK)'),
  ('Driftwood (Texas, USA)'),
  ('DubsDread Golf (Florida, USA)'),
  ('Dun Laoghaire (middle lower) (Ireland)'),
  ('Dun Laoghaire Golf Club (Upper/Lower) (Ireland)'),
  ('Dundrum Golf Club (Ireland)'),
  ('Dunston Hall (UK)'),
  ('Eagle Course at Wohali (Utah, USA)'),
  ('Eagle Crest (Michigan, USA)'),
  ('Eagle Point Golf Club (Japan)'),
  ('Eaglewood (Utah, USA)'),
  ('Echizen CC (Fukui Green TMR) (Japan)'),
  ('Eden Golf Club (UK)'),
  ('Eichenried Open.9 (Germany)'),
  ('El Dorado (Mexico)'),
  ('Elisefarm Golf Club (Sweden)'),
  ('Els Club Vilamoura (Portugal)'),
  ('Els Performance Golf Academy (Vietnam)'),
  ('Emirates Golf Estates - Faldo (Dubai, UAE)'),
  ('Emirates Golf Estates - Majlis (Dubai, UAE)'),
  ('Emporda, Dunes Course (Spain)'),
  ('Eniwa CC: Akan + Mashu (Japan)'),
  ('Eniwa CC: Mashu + Shikotsu (Japan)'),
  ('Eniwa CC: Shikotsu + Akan (Japan)'),
  ('Esbjerg Gk (Marbaek by NorSea course) (Esbjerg, Denmark)'),
  ('Escondido Golf and Lake Club (Texas, USA)'),
  ('Eskilstuna (Sweden)'),
  ('Etchinghill GC (Folkstone, England, UK)'),
  ('Evergreen Golf Centre (Canada)'),
  ('Evian Resort GC (France)'),
  ('Fairmont Chateau Whistler (Canada)'),
  ('Falmouth CC (Maine, USA)'),
  ('Fana GK (Norway)'),
  ('Fieldstone GC (Delaware, USA)'),
  ('Firekeeper GC (Kansas, USA)'),
  ('Firestone Country Club South (Ohio, USA)'),
  ('Fontana GC (Austria)'),
  ('Forsgården GK (Sweden)'),
  ('Fota Island Resort Barryscourt Course (Ireland)'),
  ('Fota Island Resort Belvelly Course (Ireland)'),
  ('Fota Island Resort Deerpark Course (Ireland)'),
  ('Foxhills Bernard Hunt (UK)'),
  ('Foxhills Bernard Hunt Course (UK)'),
  ('Foxhills Longcross (UK)'),
  ('Foyle Golf Centre (UK)'),
  ('Franklin Hills CC (Michigan, USA)'),
  ('Franklin Hills Country Club (Michigan, USA)'),
  ('Fuji Classic (Japan)'),
  ('GC Budersand (Germany)'),
  ('GC Munchen Eichenried (Germany)'),
  ('GC Murstätten (Austria)'),
  ('GC Neuhof (2 courses) (Germany)'),
  ('GC Wörthsee (Germany)'),
  ('GKG Iceland - Golfklub i Garðabær (Iceland)'),
  ('Glen Abbey CC (Canada)'),
  ('Glen Oaks Club, Tournament course (New York, USA)'),
  ('Gloria Golf Resort New Course (Turkey)'),
  ('Gloria Golf Resort Old Course (Turkey)'),
  ('Gloria Golf Resort Verde Course (Turkey)'),
  ('Golf and Country Club Berlin-Wannsee e.V. (Germany)'),
  ('Golf and More Huckingen (Germany)'),
  ('Golf Club de Genève (Switzerland)'),
  ('Golf Club Grevenmühle (Germany)'),
  ('Golf Crans sur Sierre (Switzerland)'),
  ('Golf De Joyenval (Marly Course) (France)'),
  ('Golf De Joyenval (Retz Course) (France)'),
  ('Golf De La Boulie Forest Course (France)'),
  ('Golf De La Boulie Valley Course (France)'),
  ('Golf De Saint - Cloud (Green) (France)'),
  ('Golf De Saint - Cloud (Yellow) (France)'),
  ('Golf De Seignosse (France)'),
  ('Golf Lounge Resort – Black Course (Germany)'),
  ('Golf Lounge Resort (Red Course) (Germany)'),
  ('Golf Park Holzhausern (Switzerland)'),
  ('Golf-Club Herzogenaurach (Germany)'),
  ('Golfbaan Bentwoud (27 Holes) (Netherlands)'),
  ('Golfclub Cromstrijen (18 hole course) (Netherlands)'),
  ('Golfclub Cromstrijen (9 hole course) (Netherlands)'),
  ('Golfclub Houtrak (Netherlands)'),
  ('Golfclub Kagerzoom (Dekker Warmond) (Netherlands)'),
  ('Golfklubbur Akureyrar (Iceland)'),
  ('Golfpark Moossee (Switzerland)'),
  ('Gozzer Ranch (Idaho, USA)'),
  ('Grange East (Australia)'),
  ('Grange West (Australia)'),
  ('Granite Links: Granite/Quincy (Massachusetts, USA)'),
  ('Granite Links: Milton/Granite (Massachusetts, USA)'),
  ('Granite Links: Quincy/Milton (Massachusetts, USA)'),
  ('Great Northern (Denmark)'),
  ('Great Northern Academy Course (Denmark)'),
  ('Green Valley Ranch (Colorado, USA)'),
  ('Gumbalde (Sweden)'),
  ('Gut Berge (Germany)'),
  ('Gut Kaden 27 Holes (Germany)'),
  ('Hallbrook Country Club (Kansas, USA)'),
  ('Hamilton Golf & Country Club (Ancaster, Canada)'),
  ('Hanau-Wilhelmsbad (Germany)'),
  ('Hanna Country Club (Japan)'),
  ('Happy Golfer Golfclub (Sweden)'),
  ('Hart Common Golf Club (UK)'),
  ('Hartford GC (UK)'),
  ('Haverdals Golfklubb (Sweden)'),
  ('Hawktree GC (North Dakota, USA)'),
  ('Haywards Heath (England, UK)'),
  ('Hazeltine National Golf Club (Minnesota, USA)'),
  ('Helsingør Golf Club (Denmark)'),
  ('Het Rijk Golfbanen Nijmegen Course (Netherlands)'),
  ('Het Rijk van Margraten (Netherlands)'),
  ('Hever Castle Golf Club (Championship Course) (UK)'),
  ('Hidden Canyon (Fictional)'),
  ('Hillcrest Country Club (California, USA)'),
  ('Hillcrest Short Course ''The Five'' (California, USA)'),
  ('Hillerød Golf Klub (Denmark)'),
  ('Hillerød Revision (Denmark)'),
  ('Hillside (UK)'),
  ('Hillwood CC (Tennessee, USA)'),
  ('Hilversumsche (Netherlands)'),
  ('HimmerLand Resort - New Course (Denmark)'),
  ('HimmerLand Resort - Old Course (Denmark)'),
  ('Hittfeld GC (Germany)'),
  ('Hofgut Georgenthal (Germany)'),
  ('Hofgut Scheibenhardt Golf Club (Germany)'),
  ('Hog Neck (Maryland, USA)'),
  ('Hong Kong GC (Hong Kong)'),
  ('Hooge Graven (Netherlands)'),
  ('Hualalai Golf Club (Hawaii, USA)'),
  ('Hudson National GC (New York, USA)'),
  ('Huseby & Hankø GC (Manstad, Norway)'),
  ('Innisbrook Copperhead (Florida, USA)'),
  ('Interlachen CC (Minnesota, USA)'),
  ('Interlachen Country Club (Minnesota, USA)'),
  ('Iron Horse (Montana, USA)'),
  ('JCB Golf & Country Club (UK)'),
  ('Jumeirah Golf Estates: Fire Course (Dubai, UAE)'),
  ('Kalinowe Pola GC (Poland)'),
  ('Karlstads Golfklubb (Sweden)'),
  ('Kawana Hotel Golf Course Fuji (Japan)'),
  ('Kawana Hotel Golf Course Oshima (Japan)'),
  ('Ke’olu (Hawaii, USA)'),
  ('Keilir Golf Course (Iceland)'),
  ('Kempferhof Golf Club (France)'),
  ('Keppel Club (Singapore)'),
  ('Kettle Brook Golf Club (Massachusetts, USA)'),
  ('Keya Golf Club (Japan)'),
  ('Kiawah Island Club - Cassique (South Carolina, USA)'),
  ('King Robert The Bruce, Trump Turnberry (Scotland, UK)'),
  ('Kingsfield Golf Centre (UK)'),
  ('Kissing Tree (Texas, USA)'),
  ('Kitzbühel-Schwarzsee-Reith (Austria)'),
  ('Koksijde Golf ter Hille (Belgium)'),
  ('La Dehesa (Spain)'),
  ('La Vista Country Club (Mexico)'),
  ('Lago Mar CC (Florida, USA)'),
  ('Lahinch GC (Ireland)'),
  ('Lake Geneva (Wisconsin, USA)'),
  ('Lakeside (9 holes) (UK)'),
  ('Lakewood CC (Colorado, USA)'),
  ('Landeryds Classic (Sweden)'),
  ('Landeryds Masters (Sweden)'),
  ('Landgoed Bergvliet (Netherlands)'),
  ('Landskrona Gk (Erikstorp Course) (Sweden)'),
  ('Le Golf Du Fort (France)'),
  ('Le Golf National (France)'),
  ('Le Touquet (France)'),
  ('Leatherstocking GC (New York, USA)'),
  ('Leeuwenbergh (Netherlands)'),
  ('Leon de Montana (Fictional)'),
  ('Liberty National GC (New Jersey, USA)'),
  ('Lidingö GC (Sweden)'),
  ('Linköping (Sweden)'),
  ('Lofoten Links (Norway)'),
  ('Logan Country Club (Utah, USA)'),
  ('London Gardens (Fictional)'),
  ('Long Sutton (UK)'),
  ('Longleaf Golf & Family Club (North Carolina, USA)'),
  ('Losby Ostmork Course (Norway)'),
  ('Losone GC (Switzerland)'),
  ('Lostwood Glen (Fictional)'),
  ('Lübker Golf Club (Denmark)'),
  ('Lydinge Golfklubb (Sweden)'),
  ('Machynys GC - Monk''s Island (UK)'),
  ('Madison (California, USA)'),
  ('Mainzer (Germany)'),
  ('Makena (Hawaii, USA)'),
  ('Malaro (Sweden)'),
  ('Manasquan River Golf Club (New Jersey, USA)'),
  ('Manchester Golf Club (UK)'),
  ('Marcella Club (Utah, USA)'),
  ('Marco Simone Golf and Country Club (Italy)'),
  ('Marine Drive Golf Club (Canada)'),
  ('Matsumoto Asama Country Club (Japan)'),
  ('Meadowbrook (Michigan, USA)'),
  ('Medinah (Illinois, USA)'),
  ('Meland GC (Norway)'),
  ('Miacomet Golf (Massachusetts, USA)'),
  ('Miami Lakes the Senator (Florida, USA)'),
  ('Midland Country Club (Texas, USA)'),
  ('Mieminger Plateau Golf (Austria)'),
  ('Miklagard Golf (Norway)'),
  ('Mission Hills CC (Kansas, USA)'),
  ('Modry Las GC (Poland)'),
  ('Molinetto CC (Italy)'),
  ('Montecito Club (California, USA)'),
  ('Montrêux Golf & Country Club (Nevada, USA)'),
  ('Moore Park (Australia)'),
  ('Mount Edgecombe (The Woods Course) (South Africa)'),
  ('Muirfield Village GC (Ohio, USA)'),
  ('Mullingar (UK)'),
  ('Murhof Golf Club (Austria)'),
  ('Mustafa V. Koç Golf Course (Riva GC) (Turkey)'),
  ('National Golf Romania (Romania)'),
  ('NCR Country Club South Course (Ohio, USA)'),
  ('Nemacolin Shepherds Rock (Pennsylvania, USA)'),
  ('Nemacolin, Mystic Rock (Pennsylvania, USA)'),
  ('New Golf Club - Neu-Ulm (Germany)'),
  ('Noboribetsu CC (Japan)'),
  ('Nokia River Golf River Course (Finland)'),
  ('Nokia River Golf Rocks Course (Finland)'),
  ('North at Cherokee Town & Country Club (Georgia, USA)'),
  ('North Shore Preserve (Hawaii, USA)'),
  ('Nøtterøy Golf Club (Norway)'),
  ('Nottinghamshire (UK)'),
  ('Oakdale (Canada)'),
  ('Oakmont Country Club (Pennsylvania, USA)'),
  ('Oakwood (Missouri, USA)'),
  ('Ockenburgh (9 holes) (Netherlands)'),
  ('Old Course Vilamoura (Portugal)'),
  ('Old Head Golf Links (Cork, Ireland)'),
  ('Old Macdonald (Oregon, USA)'),
  ('Old Sandwich Golf Club (Massachusetts, USA)'),
  ('Old Works (Montana, USA)'),
  ('Olympic Club Lake Course (California, USA)'),
  ('Olympic Golf Course (Brazil)'),
  ('Omanu GC (Mount Maunganui, New Zealand)'),
  ('Orchard Lake (Michigan, USA)'),
  ('Örestads Golfklubb (yellow and blue 18 holes) (Sweden)'),
  ('Östersund-Frösö Golfklubb (Sweden)'),
  ('Oswego Lake CC (Oregon, USA)'),
  ('Otelfingen (Switzerland)'),
  ('Overbrook Golf Club (Pennsylvania, USA)'),
  ('Oxbow (North Dakota, USA)'),
  ('Palmerstown House Estate (Ireland)'),
  ('Par3 Pitch & Putt Gualta (Spain)'),
  ('Paris International GC (France)'),
  ('Park Golf (Czech Republic)'),
  ('Paultons Golf Centre (UK)'),
  ('Pebble Beach "The Hay" (California, USA)'),
  ('Pebble Beach Links (California, USA)'),
  ('Penrhos Park Golf Club (UK)'),
  ('Peuramaa Golf: Porkkala Course (Finland)'),
  ('Peuramaa Golf: Vanha Peura (Finland)'),
  ('PGA Frisco - The Swing (Texas, USA)'),
  ('PGA Frisco Fields Ranch East (Texas, USA)'),
  ('PGA Frisco Fields Ranch West (Texas, USA)'),
  ('PGA National (Florida, USA)'),
  ('PGA West - Dye Mountain (California, USA)'),
  ('PGA West - Dye Stadium (California, USA)'),
  ('PGA West Nicklaus Tournament course (California, USA)'),
  ('Phoenix CC Nichinan - Takachiho (Japan)'),
  ('Phoenix CC Sumiyoshi - Nichinan (Japan)'),
  ('Phoenix CC Takachiho - Sumiyoshi (Japan)'),
  ('Pine Brook CC (Massachusetts, USA)'),
  ('Pinehurst Cradle (North Carolina, USA)'),
  ('Pinehurst No. 2 (North Carolina, USA)'),
  ('Plainfield CC (New Jersey, USA)'),
  ('Playa Grande (Dominican Republic)'),
  ('Pokegama (Minnesota, USA)'),
  ('Port Huron GC (Michigan, USA)'),
  ('Portland Golf Club (Oregon, USA)'),
  ('Prairie Bluff (Illinois, USA)'),
  ('Primland (Virginia, USA)'),
  ('Princenbosch (27 holes - 3 versions) (Netherlands)'),
  ('Promontory (Dye Course) (Utah, USA)'),
  ('Promontory (Nicklaus) (Utah, USA)'),
  ('Qiddiya Faldo (Saudi Arabia)'),
  ('Quail Hollow Club (North Carolina, USA)'),
  ('Quaker Ridge GC (New York, USA)'),
  ('Quarry Ridge (Connecticut, USA)'),
  ('Rae Golf (Estonia)'),
  ('Real Club Valderrama (Spain)'),
  ('Reykjavik Grafarholt (Iceland)'),
  ('Reykjavik Korpa Ain/Landid (Iceland)'),
  ('Reykjavik Korpa Sjorinn/Ain (Iceland)'),
  ('Reykjavik Korpa Sjorinn/Landio (Iceland)'),
  ('Richland CC (Tennessee, USA)'),
  ('Ridgewood CC, Championship (New Jersey, USA)'),
  ('Riverside Country Club (Canada)'),
  ('Riyadh Golf Club – LIV Edition'),
  ('Riyadh Golf Course (Saudi Arabia)'),
  ('Rochester (Minnesota, USA)'),
  ('Rock Golf (Finland)'),
  ('Rockledge Golf Club (West Hartford, Connecticut, USA)'),
  ('Romanby Golf & Country Club (UK)'),
  ('Rönnebeck Hinton (Sweden)'),
  ('Royal Birkdale (UK)'),
  ('Royal County Down (UK)'),
  ('Royal Dornoch (Championship Course) (UK)'),
  ('Royal Drottningholm GC (Sweden)'),
  ('Royal Homburger GC (Germany)'),
  ('Royal Melbourne Golf Club Composite (Australia)'),
  ('Royal Melbourne Golf Club East (Australia)'),
  ('Royal Melbourne Golf Club West (Australia)'),
  ('Royal Ostend GC (Belgium)'),
  ('Royal Ottowa (Canada)'),
  ('Royal Portrush - Dunluce Links (UK)'),
  ('Royal St Georges (UK)'),
  ('Royal Troon (UK)'),
  ('Rungsted Golf Club (Denmark)'),
  ('Rya GK Old Course (Sweden)'),
  ('Sand River (Fictional)'),
  ('Sand Valley - Mammoth Dunes (Wisconsin, USA)'),
  ('Sand Valley - Sedge Valley (Wisconsin, USA)'),
  ('Sand Valley - The Lido (Wisconsin, USA)'),
  ('Sand Valley (Wisconsin, USA)'),
  ('Schloss Pichlarn (Austria)'),
  ('Schloss-Platz (Germany)'),
  ('Scioto Country Club (Ohio, USA)'),
  ('Scioto Country Club Pre-Restoration (Ohio, USA)'),
  ('Sea Island (Seaside) (Georgia, USA)'),
  ('Sea Island Plantation (Georgia, USA)'),
  ('Sea Island Seaside (Georgia, USA)'),
  ('Sea Island Seaside (rebuild) (Georgia, USA)'),
  ('Sebonack (New York, USA)'),
  ('Sembawang Country Club (Singapore)'),
  ('Senoja Valley (Fictional)'),
  ('Sentosa (Serapong) (Singapore)'),
  ('Seve GC Rotterdam (Netherlands)'),
  ('Shadowlands (Fictional)'),
  ('Shangri La Resort, Champions/Heritage (Oklahoma, USA)'),
  ('Shangri La Resort, Heritage/Legends (Oklahoma, USA)'),
  ('Shangri La Resort, Legends/Champions (Oklahoma, USA)'),
  ('Sharpley Golf Club (UK)'),
  ('Shaughnessy Golf & Country Club (Canada)'),
  ('Shelter Harbor (Rhode Island, USA)'),
  ('Shishido Hills (Japan)'),
  ('Shizu Hills Country Club (Japan)'),
  ('Shooting Star (Wyoming, USA)'),
  ('Silo Ridge (New York, USA)'),
  ('Silverleaf Club (Arizona, USA)'),
  ('Skerike Golfklubb (Sweden)'),
  ('Slinfold Golf & Country Club (UK)'),
  ('Sola Golfklubb - Forus Course (Norway)'),
  ('Sola Golfklubb (Solastranden Course) (Norway)'),
  ('Southview CC (Minnesota, USA)'),
  ('Spyglass Hill (California, USA)'),
  ('St Andrews Links Castle Course (UK)'),
  ('St Andrews Links Jubilee Course (UK)'),
  ('St Andrews Links New Course (UK)'),
  ('St Andrews Links Old Course (UK)'),
  ('St Clair Country Club Championship Course (Pennsylvania, USA)'),
  ('St Clair Country Club Terrace Course (Pittsburgh, Pennsylvania, USA)'),
  ('St Georges (Canada)'),
  ('Stavanger Golfklubb (Norway)'),
  ('Stensballegaard (27 Holes) (Denmark)'),
  ('Steyn City (South Africa)'),
  ('Stjordal (Norway)'),
  ('Stock Brook Country Club (UK)'),
  ('Stoneham (UK)'),
  ('Strandtorp (9 holes) (Sweden)'),
  ('Stratford Oaks (UK)'),
  ('Stuttgarter Golf-Club Solitude (Germany)'),
  ('Sutton Bay (South Dakota, USA)'),
  ('Sutton Bay Short Course (South Dakota, USA)'),
  ('Suvarna Jakarta Golf Club (27 holes) (Indonesia)'),
  ('Sweetens Cove (Tennessee, USA)'),
  ('Syke (Germany)'),
  ('Tacoma C&GC (Washington, USA)'),
  ('Taiheiyo Club Gotemba Course (Japan)'),
  ('Taiheiyo/Minori (Japan)'),
  ('Tapiola GC (Finland)'),
  ('The Aces Club (Fictional)'),
  ('The Camellia Course at Killearn Club (Florida, USA)'),
  ('The Cardinal at Saint John’s Resort (Michigan, USA)'),
  ('The Club at Olde Stone (Kentucky, USA)'),
  ('The Club at Olde Stone (Sink Hole) 9 (Kentucky, USA)'),
  ('The Concession GC (Florida, USA)'),
  ('The Drift (UK)'),
  ('The Duke Club (Netherlands)'),
  ('The Grove (UK)'),
  ('The Heather at Boyne Highlands (Michigan, USA)'),
  ('The Hideaway Clive Clark (California, USA)'),
  ('The Hideaway Pete Dye (California, USA)'),
  ('The International (Netherlands)'),
  ('The K Club: The Palmer North Course (Ireland)'),
  ('The Links at Spanish Bay (Florida, USA)'),
  ('The Lost 9 (Fictional)'),
  ('The National Golf (Belgium)'),
  ('The National Lakes (Sweden)'),
  ('The National Links (Sweden)'),
  ('The Reserve at Moonlight Basin (Montana, USA)'),
  ('The Ridge Golf Club (UK)'),
  ('The Royal Golf Club (Bahrain)'),
  ('The Royal Montreal Golf Club Blue Course (Canada)'),
  ('The Royal Sydney Golf Club Championship Course (Australia)'),
  ('The Springhaven Club (Pennsylvania, USA)'),
  ('The Summit Club (Nevada, USA)'),
  ('The Swing Short Course (Texas, USA)'),
  ('The Valley Course at Crane Valley Golf Club (UK)'),
  ('Thumper Pond Golf Course (Minnesota, USA)'),
  ('Timberline GC (Alabama, USA)'),
  ('Timrå GK (Sweden)'),
  ('Tokyo Gardens (Fictional)'),
  ('TPC Colorado (Colorado, USA)'),
  ('Tranås Golfklubb (Sweden)'),
  ('Tributary (Idaho, USA)'),
  ('Trinity Forest Golf Club (Texas, USA)'),
  ('Troubadour TN (Tennessee, USA)'),
  ('Troxhammar (Sweden)'),
  ('Trump Dubai (UAE)'),
  ('Turning Stone (Atunyote Course) (New York, USA)'),
  ('Turning Stone (Shenendoah Course) (New York, USA)'),
  ('Union League Liberty Hill (Pennsylvania, USA)'),
  ('Union League Torresdale (Pennsylvania, USA)'),
  ('Valhalla GC (Kentucky, USA)'),
  ('Vallda (Sweden)'),
  ('Varbergs GK (Sweden)'),
  ('Vasatorp Tournament Course (Sweden)'),
  ('Vattanac East (Cambodia)'),
  ('Vattanac West (Cambodia)'),
  ('Växjö Golfklubb (18 hole course) (Sweden)'),
  ('Visby Gk (Sweden)'),
  ('Wabeek C.C. (Michigan, USA)'),
  ('Wachusett Country Club (Massachusetts, USA)'),
  ('Wayzata CC (Minnesota, USA)'),
  ('Webster (New York, USA)'),
  ('Wembley G.C Old course (Australia)'),
  ('Wentworth GC (West Course) (UK)'),
  ('West Essex (UK)'),
  ('Weston Golf and Country Club (Canada)'),
  ('WGC Gütersloh (Germany)'),
  ('Whistle Bear Golf Club (Canada)'),
  ('Whistler Golf Club (Canada)'),
  ('White Bear Yacht Club (Minnesota, USA)'),
  ('Whitetail Ridge (Illinois, USA)'),
  ('Wilshire Country Club (California, USA)'),
  ('Woodmont Country Club - North Course (Maryland, USA)'),
  ('Worcester Country Club (Massachusetts, USA)'),
  ('Wyboston Lakes Resort (UK)'),
  ('Wychwood Golf Club (UK)'),
  ('Wylihof Golf (27 holes) (Switzerland)'),
  ('Wyndemere CC (Gold/Green) (Florida, USA)'),
  ('Wyndemere CC (Green/White) (Florida, USA)'),
  ('Wyndemere CC (White/Gold) (Florida, USA)'),
  ('Y-Brig (Switzerland)'),
  ('Yellowstone Club (Montana, USA)'),
  ('Zeegersloot Golf Club (Netherlands)'),
  ('Zillertal-Uderns Golf Club (Austria)'),
  ('Zwartkop Country Club (South Africa)')
on conflict (name) do nothing;
